services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      FORKS: 1
      NODE_ENV: development # todo -> change to production
      PORT: 3000
      DB_LOCATION: ./data/robotswebsite.db
    # volumes:
    #   - ./app:/stackzero/app
    #   - ./core:/stackzero/core
    # env_file:
    #   - .env
